pipeline {
    agent {
        label 'agent1'
    }
  
    stages { 
        stage("checkout scm") {
            steps {
                git credentialsId: 'jenkins-project-repo',url:"https://github.com/mishti30/jenkins-project.git", branch: "dockercompose"
            }
        }
        stage("build Image") { 
            steps {

                sh "docker build -t myphpimg:latest ."
            }
        }
        stage("Container Create") {
            steps {
                sh "docker-compose up -d "
            }
        }
    }
}